// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dekrfjjqytctalkavrxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRla3JmampxeXRjdGFsa2F2cnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTQxODYsImV4cCI6MjA3MDA3MDE4Nn0.s72tbHifTZWipO2yk8fcy6i3PBiKlQYKPPuiCfvbdZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});